server:
  port: 8080
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test22?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000

#pojo别名扫描包
mybatis:
  type-aliases-package: com.example.chatroom.domain.User
pagehelper:
    helper-dialect: mysql

